language : node_js
node_js:
 - "10"
install:
- npm install
os:
 - linux

stages:
 - test
#  - name: deploy

jobs:
 include:
   - stage: test
     script:
       - node --version
       - npm --version
       - echo "Testing Started ..."
       - npm test
       - echo "Testing Finished."

  #  - stage: deploy
  #    script:
  #      - echo "NPM Deploying Started ..."
  #      - npm version
  #      - npm run build
  #      - echo "NPM Building Finished."

     test:
       provider: npm
       email: pamki@sina.com
       api_key: "$NPM_TOKEN"
       skip_cleanup: true
       on:
         all_branches: true